'use scrict';
let divFirst = document.querySelector('#first');
divFirst.style.backgroundColor = 'red';
let divSecond = document.querySelector('#second');
divSecond.style.backgroundColor = 'blue';
let divsYellow = document.querySelectorAll('.yellow');
divsYellow[0].style.backgroundColor = 'yellow';
divsYellow[2].style.backgroundColor = 'yellow';
let divs = document.querySelectorAll('div');
divs[3].style.backgroundColor = 'green';
